USE [master]
GO

/****** Object:  Database [sozDbUser]    Script Date: 4/28/2023 10:49:03 PM ******/
CREATE DATABASE [sozDbUser]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sozDbUser', FILENAME = N'/var/opt/mssql/data/sozDbUser.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sozDbUser_log', FILENAME = N'/var/opt/mssql/data/sozDbUser_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sozDbUser].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sozDbUser] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sozDbUser] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sozDbUser] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sozDbUser] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sozDbUser] SET ARITHABORT OFF 
GO

ALTER DATABASE [sozDbUser] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sozDbUser] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sozDbUser] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sozDbUser] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sozDbUser] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sozDbUser] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sozDbUser] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sozDbUser] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sozDbUser] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sozDbUser] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sozDbUser] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sozDbUser] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sozDbUser] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sozDbUser] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sozDbUser] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sozDbUser] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sozDbUser] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sozDbUser] SET RECOVERY FULL 
GO

ALTER DATABASE [sozDbUser] SET  MULTI_USER 
GO

ALTER DATABASE [sozDbUser] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sozDbUser] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sozDbUser] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sozDbUser] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [sozDbUser] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sozDbUser] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [sozDbUser] SET QUERY_STORE = OFF
GO

ALTER DATABASE [sozDbUser] SET  READ_WRITE 
GO

