USE [master]
GO

/****** Object:  Database [sozDB]    Script Date: 5/14/2023 8:34:40 AM ******/
CREATE DATABASE [sozDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sozDB', FILENAME = N'/var/opt/mssql/data/sozDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sozDB_log', FILENAME = N'/var/opt/mssql/data/sozDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sozDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sozDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sozDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sozDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sozDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sozDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [sozDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sozDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sozDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sozDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sozDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sozDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sozDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sozDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sozDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sozDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sozDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sozDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sozDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sozDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sozDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sozDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sozDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sozDB] SET RECOVERY FULL 
GO

ALTER DATABASE [sozDB] SET  MULTI_USER 
GO

ALTER DATABASE [sozDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sozDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sozDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sozDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [sozDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sozDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [sozDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [sozDB] SET  READ_WRITE 
GO

